{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pymongo\n",
    "import json\n",
    "import os\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "src_path = os.path.join('..','data', 'clean', 'median_income_black.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "..\\data\\clean\\median_income_black.csv\n"
     ]
    }
   ],
   "source": [
    "print(src_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>Black</th>\n",
       "      <th>TableReferenceId</th>\n",
       "      <th>CensusNotes</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>County</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>Schoharie County</th>\n",
       "      <td>0500000US36095</td>\n",
       "      <td>63750</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Onondaga County</th>\n",
       "      <td>0500000US36067</td>\n",
       "      <td>31623</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Clinton County</th>\n",
       "      <td>0500000US36019</td>\n",
       "      <td>50208</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Seneca County</th>\n",
       "      <td>0500000US36099</td>\n",
       "      <td>36094</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Putnam County</th>\n",
       "      <td>0500000US36079</td>\n",
       "      <td>98875</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Greene County</th>\n",
       "      <td>0500000US36039</td>\n",
       "      <td>64026</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Allegany County</th>\n",
       "      <td>0500000US36003</td>\n",
       "      <td>41406</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Cattaraugus County</th>\n",
       "      <td>0500000US36009</td>\n",
       "      <td>-</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Schenectady County</th>\n",
       "      <td>0500000US36093</td>\n",
       "      <td>31813</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Yates County</th>\n",
       "      <td>0500000US36123</td>\n",
       "      <td>-</td>\n",
       "      <td>B19013B</td>\n",
       "      <td>median income</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>62 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                id  Black TableReferenceId   CensusNotes \n",
       "County                                                                   \n",
       "Schoharie County    0500000US36095  63750          B19013B  median income\n",
       "Onondaga County     0500000US36067  31623          B19013B  median income\n",
       "Clinton County      0500000US36019  50208          B19013B  median income\n",
       "Seneca County       0500000US36099  36094          B19013B  median income\n",
       "Putnam County       0500000US36079  98875          B19013B  median income\n",
       "...                            ...    ...              ...            ...\n",
       "Greene County       0500000US36039  64026          B19013B  median income\n",
       "Allegany County     0500000US36003  41406          B19013B  median income\n",
       "Cattaraugus County  0500000US36009      -          B19013B  median income\n",
       "Schenectady County  0500000US36093  31813          B19013B  median income\n",
       "Yates County        0500000US36123      -          B19013B  median income\n",
       "\n",
       "[62 rows x 4 columns]"
      ]
     },
     "execution_count": 101,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = pd.read_csv(src_path)\n",
    "data.set_index(['County'], inplace = True, \n",
    "                    append = False, drop = True)\n",
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "County\n",
       "Schoharie County      63750\n",
       "Onondaga County       31623\n",
       "Clinton County        50208\n",
       "Seneca County         36094\n",
       "Putnam County         98875\n",
       "                      ...  \n",
       "Greene County         64026\n",
       "Allegany County       41406\n",
       "Cattaraugus County        -\n",
       "Schenectady County    31813\n",
       "Yates County              -\n",
       "Name: Black, Length: 62, dtype: object"
      ]
     },
     "execution_count": 102,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data['Black']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'id': {'Schoharie County': '0500000US36095',\n",
       "  'Onondaga County': '0500000US36067',\n",
       "  'Clinton County': '0500000US36019',\n",
       "  'Seneca County': '0500000US36099',\n",
       "  'Putnam County': '0500000US36079',\n",
       "  'Franklin County': '0500000US36033',\n",
       "  'Ontario County': '0500000US36069',\n",
       "  'Queens County': '0500000US36081',\n",
       "  'Steuben County': '0500000US36101',\n",
       "  'Hamilton County': '0500000US36041',\n",
       "  'Washington County': '0500000US36115',\n",
       "  'Chautauqua County': '0500000US36013',\n",
       "  'Kings County': '0500000US36047',\n",
       "  'New York County': '0500000US36061',\n",
       "  'Tioga County': '0500000US36107',\n",
       "  'Cayuga County': '0500000US36011',\n",
       "  'Orleans County': '0500000US36073',\n",
       "  'Saratoga County': '0500000US36091',\n",
       "  'Rockland County': '0500000US36087',\n",
       "  'Columbia County': '0500000US36021',\n",
       "  'Lewis County': '0500000US36049',\n",
       "  'Niagara County': '0500000US36063',\n",
       "  'Westchester County': '0500000US36119',\n",
       "  'Delaware County': '0500000US36025',\n",
       "  'Essex County': '0500000US36031',\n",
       "  'Montgomery County': '0500000US36057',\n",
       "  'Nassau County': '0500000US36059',\n",
       "  'Richmond County': '0500000US36085',\n",
       "  'Schuyler County': '0500000US36097',\n",
       "  'Tompkins County': '0500000US36109',\n",
       "  'Chenango County': '0500000US36017',\n",
       "  'Cortland County': '0500000US36023',\n",
       "  'Jefferson County': '0500000US36045',\n",
       "  'Oneida County': '0500000US36065',\n",
       "  'Suffolk County': '0500000US36103',\n",
       "  'Wyoming County': '0500000US36121',\n",
       "  'Chemung County': '0500000US36015',\n",
       "  'Oswego County': '0500000US36075',\n",
       "  'Otsego County': '0500000US36077',\n",
       "  'Wayne County': '0500000US36117',\n",
       "  'Albany County': '0500000US36001',\n",
       "  'Broome County': '0500000US36007',\n",
       "  'Erie County': '0500000US36029',\n",
       "  'Madison County': '0500000US36053',\n",
       "  'Sullivan County': '0500000US36105',\n",
       "  'Genesee County': '0500000US36037',\n",
       "  'Orange County': '0500000US36071',\n",
       "  'Bronx County': '0500000US36005',\n",
       "  'Fulton County': '0500000US36035',\n",
       "  'Rensselaer County': '0500000US36083',\n",
       "  'Dutchess County': '0500000US36027',\n",
       "  'Herkimer County': '0500000US36043',\n",
       "  'St. Lawrence County': '0500000US36089',\n",
       "  'Warren County': '0500000US36113',\n",
       "  'Monroe County': '0500000US36055',\n",
       "  'Ulster County': '0500000US36111',\n",
       "  'Livingston County': '0500000US36051',\n",
       "  'Greene County': '0500000US36039',\n",
       "  'Allegany County': '0500000US36003',\n",
       "  'Cattaraugus County': '0500000US36009',\n",
       "  'Schenectady County': '0500000US36093',\n",
       "  'Yates County': '0500000US36123'},\n",
       " 'Black': {'Schoharie County': '63750',\n",
       "  'Onondaga County': '31623',\n",
       "  'Clinton County': '50208',\n",
       "  'Seneca County': '36094',\n",
       "  'Putnam County': '98875',\n",
       "  'Franklin County': '-',\n",
       "  'Ontario County': '32037',\n",
       "  'Queens County': '66562',\n",
       "  'Steuben County': '45045',\n",
       "  'Hamilton County': '-',\n",
       "  'Washington County': '-',\n",
       "  'Chautauqua County': '19898',\n",
       "  'Kings County': '45326',\n",
       "  'New York County': '35596',\n",
       "  'Tioga County': '71477',\n",
       "  'Cayuga County': '29821',\n",
       "  'Orleans County': '45938',\n",
       "  'Saratoga County': '68675',\n",
       "  'Rockland County': '76649',\n",
       "  'Columbia County': '36029',\n",
       "  'Lewis County': '-',\n",
       "  'Niagara County': '26330',\n",
       "  'Westchester County': '59181',\n",
       "  'Delaware County': '25658',\n",
       "  'Essex County': '-',\n",
       "  'Montgomery County': '35517',\n",
       "  'Nassau County': '94498',\n",
       "  'Richmond County': '46065',\n",
       "  'Schuyler County': '-',\n",
       "  'Tompkins County': '29674',\n",
       "  'Chenango County': '71613',\n",
       "  'Cortland County': '-',\n",
       "  'Jefferson County': '50945',\n",
       "  'Oneida County': '27389',\n",
       "  'Suffolk County': '76115',\n",
       "  'Wyoming County': '47639',\n",
       "  'Chemung County': '29871',\n",
       "  'Oswego County': '-',\n",
       "  'Otsego County': '42772',\n",
       "  'Wayne County': '27692',\n",
       "  'Albany County': '32005',\n",
       "  'Broome County': '22036',\n",
       "  'Erie County': '30686',\n",
       "  'Madison County': '63500',\n",
       "  'Sullivan County': '40198',\n",
       "  'Genesee County': '28750',\n",
       "  'Orange County': '66549',\n",
       "  'Bronx County': '40681',\n",
       "  'Fulton County': '-',\n",
       "  'Rensselaer County': '31610',\n",
       "  'Dutchess County': '50765',\n",
       "  'Herkimer County': '-',\n",
       "  'St. Lawrence County': '75500',\n",
       "  'Warren County': '74028',\n",
       "  'Monroe County': '30034',\n",
       "  'Ulster County': '32085',\n",
       "  'Livingston County': '21333',\n",
       "  'Greene County': '64026',\n",
       "  'Allegany County': '41406',\n",
       "  'Cattaraugus County': '-',\n",
       "  'Schenectady County': '31813',\n",
       "  'Yates County': '-'},\n",
       " 'TableReferenceId': {'Schoharie County': 'B19013B',\n",
       "  'Onondaga County': 'B19013B',\n",
       "  'Clinton County': 'B19013B',\n",
       "  'Seneca County': 'B19013B',\n",
       "  'Putnam County': 'B19013B',\n",
       "  'Franklin County': 'B19013B',\n",
       "  'Ontario County': 'B19013B',\n",
       "  'Queens County': 'B19013B',\n",
       "  'Steuben County': 'B19013B',\n",
       "  'Hamilton County': 'B19013B',\n",
       "  'Washington County': 'B19013B',\n",
       "  'Chautauqua County': 'B19013B',\n",
       "  'Kings County': 'B19013B',\n",
       "  'New York County': 'B19013B',\n",
       "  'Tioga County': 'B19013B',\n",
       "  'Cayuga County': 'B19013B',\n",
       "  'Orleans County': 'B19013B',\n",
       "  'Saratoga County': 'B19013B',\n",
       "  'Rockland County': 'B19013B',\n",
       "  'Columbia County': 'B19013B',\n",
       "  'Lewis County': 'B19013B',\n",
       "  'Niagara County': 'B19013B',\n",
       "  'Westchester County': 'B19013B',\n",
       "  'Delaware County': 'B19013B',\n",
       "  'Essex County': 'B19013B',\n",
       "  'Montgomery County': 'B19013B',\n",
       "  'Nassau County': 'B19013B',\n",
       "  'Richmond County': 'B19013B',\n",
       "  'Schuyler County': 'B19013B',\n",
       "  'Tompkins County': 'B19013B',\n",
       "  'Chenango County': 'B19013B',\n",
       "  'Cortland County': 'B19013B',\n",
       "  'Jefferson County': 'B19013B',\n",
       "  'Oneida County': 'B19013B',\n",
       "  'Suffolk County': 'B19013B',\n",
       "  'Wyoming County': 'B19013B',\n",
       "  'Chemung County': 'B19013B',\n",
       "  'Oswego County': 'B19013B',\n",
       "  'Otsego County': 'B19013B',\n",
       "  'Wayne County': 'B19013B',\n",
       "  'Albany County': 'B19013B',\n",
       "  'Broome County': 'B19013B',\n",
       "  'Erie County': 'B19013B',\n",
       "  'Madison County': 'B19013B',\n",
       "  'Sullivan County': 'B19013B',\n",
       "  'Genesee County': 'B19013B',\n",
       "  'Orange County': 'B19013B',\n",
       "  'Bronx County': 'B19013B',\n",
       "  'Fulton County': 'B19013B',\n",
       "  'Rensselaer County': 'B19013B',\n",
       "  'Dutchess County': 'B19013B',\n",
       "  'Herkimer County': 'B19013B',\n",
       "  'St. Lawrence County': 'B19013B',\n",
       "  'Warren County': 'B19013B',\n",
       "  'Monroe County': 'B19013B',\n",
       "  'Ulster County': 'B19013B',\n",
       "  'Livingston County': 'B19013B',\n",
       "  'Greene County': 'B19013B',\n",
       "  'Allegany County': 'B19013B',\n",
       "  'Cattaraugus County': 'B19013B',\n",
       "  'Schenectady County': 'B19013B',\n",
       "  'Yates County': 'B19013B'},\n",
       " 'CensusNotes ': {'Schoharie County': 'median income',\n",
       "  'Onondaga County': 'median income',\n",
       "  'Clinton County': 'median income',\n",
       "  'Seneca County': 'median income',\n",
       "  'Putnam County': 'median income',\n",
       "  'Franklin County': 'median income',\n",
       "  'Ontario County': 'median income',\n",
       "  'Queens County': 'median income',\n",
       "  'Steuben County': 'median income',\n",
       "  'Hamilton County': 'median income',\n",
       "  'Washington County': 'median income',\n",
       "  'Chautauqua County': 'median income',\n",
       "  'Kings County': 'median income',\n",
       "  'New York County': 'median income',\n",
       "  'Tioga County': 'median income',\n",
       "  'Cayuga County': 'median income',\n",
       "  'Orleans County': 'median income',\n",
       "  'Saratoga County': 'median income',\n",
       "  'Rockland County': 'median income',\n",
       "  'Columbia County': 'median income',\n",
       "  'Lewis County': 'median income',\n",
       "  'Niagara County': 'median income',\n",
       "  'Westchester County': 'median income',\n",
       "  'Delaware County': 'median income',\n",
       "  'Essex County': 'median income',\n",
       "  'Montgomery County': 'median income',\n",
       "  'Nassau County': 'median income',\n",
       "  'Richmond County': 'median income',\n",
       "  'Schuyler County': 'median income',\n",
       "  'Tompkins County': 'median income',\n",
       "  'Chenango County': 'median income',\n",
       "  'Cortland County': 'median income',\n",
       "  'Jefferson County': 'median income',\n",
       "  'Oneida County': 'median income',\n",
       "  'Suffolk County': 'median income',\n",
       "  'Wyoming County': 'median income',\n",
       "  'Chemung County': 'median income',\n",
       "  'Oswego County': 'median income',\n",
       "  'Otsego County': 'median income',\n",
       "  'Wayne County': 'median income',\n",
       "  'Albany County': 'median income',\n",
       "  'Broome County': 'median income',\n",
       "  'Erie County': 'median income',\n",
       "  'Madison County': 'median income',\n",
       "  'Sullivan County': 'median income',\n",
       "  'Genesee County': 'median income',\n",
       "  'Orange County': 'median income',\n",
       "  'Bronx County': 'median income',\n",
       "  'Fulton County': 'median income',\n",
       "  'Rensselaer County': 'median income',\n",
       "  'Dutchess County': 'median income',\n",
       "  'Herkimer County': 'median income',\n",
       "  'St. Lawrence County': 'median income',\n",
       "  'Warren County': 'median income',\n",
       "  'Monroe County': 'median income',\n",
       "  'Ulster County': 'median income',\n",
       "  'Livingston County': 'median income',\n",
       "  'Greene County': 'median income',\n",
       "  'Allegany County': 'median income',\n",
       "  'Cattaraugus County': 'median income',\n",
       "  'Schenectady County': 'median income',\n",
       "  'Yates County': 'median income'}}"
      ]
     },
     "execution_count": 103,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dict = data.to_dict()\n",
    "dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0500000US36095\n",
      "Schoharie County\n",
      "63750\n",
      "B19013B\n",
      "median income\n"
     ]
    }
   ],
   "source": [
    "for row in dict:\n",
    "    \n",
    "    print(dict[row][0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "dbclient = pymongo.MongoClient('mongodb://localhost:27017/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "metadata": {},
   "outputs": [],
   "source": [
    "db = dbclient['nycares_db']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [],
   "source": [
    "dbcol = db['median_data']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-------------------------------------------------------------------------\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "string indices must be integers",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-76-1f0af14018c9>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'-------------------------------------------------------------------------'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m     \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrow\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'id'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m: string indices must be integers"
     ]
    }
   ],
   "source": [
    "for row in dict:\n",
    "    \n",
    "    print('-------------------------------------------------------------------------')\n",
    "    print(row['id'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
